blueprint:
  name: Tuya Zigbee Rotary Dial (Z2M) → Light Dimmer
  description: >
    Map a Tuya Zigbee rotary dial (via Zigbee2MQTT) to control a light:
    - Single press: toggle (configurable)
    - Double press: max brightness (configurable)
    - Hold: min brightness / off (configurable)
    - Rotate right/left: brightness up/down with step (%) or device-reported step size
    Supports both JSON payloads on zigbee2mqtt/<device> and plain text on zigbee2mqtt/<device>/action.
  domain: automation
  source_url: https://example.invalid/tuya-rotary-z2m-blueprint

  input:
    z2m_topic:
      name: Zigbee2MQTT device topic
      description: Enter the exact device topic, e.g. zigbee2mqtt/tuya_dial (no trailing /action).
      selector:
        text: {}
    light_target:
      name: Light to control
      selector:
        target:
          entity:
            domain: light
    step_pct:
      name: Brightness step per tick (%)
      description: Used when the device doesn't provide action_step_size.
      default: 7
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
          mode: slider
    use_device_step:
      name: Use device-reported step size when available
      description: If your dial sends "action_step_size", use it (scaled to %).
      default: true
      selector:
        boolean: {}
    onpress_action:
      n
